src/api.ts
src/plugin.ts
src/util.ts

We probably want to trigger a full re-authentication when the server metadata does not match the metadata we had used for a previous authentication event.
Also, clarify a note about the current state of this plugin with regards to being able to pass it to multiple MongoClient instances. (This does not affect DevTools as we currently do not have plans to re-use OIDC plugin instances across different MongoDB endpoints at the same time, but may be relevant for other users as well as our future selves.)

fix: use full OIDC server metadata as cache key MONGOSH-1434

---

src/integration.spec.ts

I completely forgot that OIDC was just not planned as a supported server feature outside of Linux when writing the previous `TODO` comments. Other than that, updating the version here to point to the 7.0.0 rcs does make sense.

fix: use 7.0.0-rc version for integration tests MONGOSH-1436

---

src/api.ts
src/log-hook.ts
src/plugin.spec.ts
src/plugin.ts
src/types.ts

So that we can e.g. store the state in Compass as properties of the connection data and can use a refresh token from a previous session if the IdP allows that.

feat: add support for serializing/deserializing plugin state MONGOSH-1400

---

src/api.ts
src/index.ts
src/plugin.spec.ts
src/plugin.ts

This should enable us to display a modal in Compass when re-authentication is required after the initial auth, and prompt the user whether they want to reauthenticate or just return to the connection screen again.

feat: allow dynamic async/rejectable allowedFlows COMPASS-6811

---

README.md
src/api.ts
src/plugin.spec.ts
src/plugin.ts

In WRITING-14037, one of the items for driver OIDC callbacks was:
> Recommend considering whether to allow Device Authorization Grant
In mongosh and Compass, we do not want to enable this by default. To make it easier for other Node.js driver users to also use the same defaults as us, let’s flip the default here in the plugin.

feat: do not enable device-auth flow by default

---

src/plugin.ts

The URL that is passed to the browser in our plugin is generated by us, so we are in control over the format of it. This commit adds another check that that format is still intact right before we open the browser, so that e.g. a future developer who wants to remove our redirect would not be able to accidentally introduce a security issue by letting URLs pass through which contain characters with special semantics in the shell (e.g. `&` in a query string).

chore: do slightly stricter URL validation

---

package-lock.json
package.json
src/plugin.ts

Previously, the `.finally()` call would create a second promise chain, whose results were never handled, so a rejection in `newAuthAttempt` would lead to an unhandled rejection warning/error.
Fixes: https://github.com/mongodb-js/oidc-plugin/pull/49

fix: do not let auth failure bubble up as unhandled rejection

---

src/plugin.spec.ts
src/plugin.ts

Otherwise, this callback is not useful as an indicator for re-authentication.

fix: only call auth flow selection cb before human auth

---

src/types.ts

We don’t make use of this in the plugin’s own code, but it can be convenient for downstream users to know that this method may be there (e.g. when accessing a plugin’s `.logger` property).

chore: add optional .off to TypedEventEmitter

---

package-lock.json
package.json
src/api.ts
src/index.ts
src/log-hook.ts
src/plugin.spec.ts
src/plugin.ts
src/rfc-8252-http-server.ts
src/types.ts
src/util.ts

The commits here are fairly independent (and can be reviewed indepedently), but they would otherwise be fairly small changes or conflict with each other, so this is just one big PR to handle all of them together. If it's easier, I'm happy to split them out and PR them sequentially as well 🙂 
(This would be used to implement `useSystemCA` support in devtools-connect)

feat: improve diagnostics, allow custom HTTP options, account for IdP support for scopes

---

src/api.ts
src/log-hook.ts
src/plugin.spec.ts
src/plugin.ts
src/types.ts
src/util.ts
test/log-hook-verification-helpers.ts

Miscellaneous improvements around logging inside the plugin, plus a few preparations
for downstream diagnostics improvements:
- Emit an event when the browser has successfully been opened (COMPASS-8121)
- Improve logging around token refreshing (MONGOSH-1795)
- Emit acquired tokens in an event (MONGOSH-1845)
- Use `.timers` for also testing the browser timer

feat: improve logging and testing, allow using id tokens instead of access tokens

---

src/plugin.spec.ts
src/plugin.ts
src/types.ts

This is something we should have ideally always been doing (as hinted at by the doc comment for `getAuthState()`), but which the driver only added back support for in 6.7.0.
This shouldn't have an immediate impact on our products, because we already have some mitigations in place for the fact that usernames were previously not being taken into account (e.g. here:
https://github.com/mongodb-js/mongosh/blob/adc530e7ffcf092677d944fd69670c5cbd8e103d/packages/service-provider-server/src/cli-service-provider.ts#L172 ), but is semantically the right thing to do and should give us a bit more flexibility in the future.
Also, add a test that confirms that changes to server metadata/username actually have the expected effect, and emit a message bus event that shares information about the server …

fix: include username in server metadata key

---

package-lock.json
package.json
src/api.ts
src/plugin.spec.ts
src/plugin.ts
test/oidc-test-provider.ts

Needs https://github.com/mongodb-js/devtools-shared/pull/489 for tests to pass.

fix: always send a nonce in the auth request MONGOSH-1905

---

.github/workflows/nodejs.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml

This PR adds the following:
1. A "Prepare Release" workflow that can be invoked with an update type (patch/minor/major). Once run, it will bump the package version, create a `release/version` branch, and open a PR.
2. A `package` job for the PR workflow. This is run only on `release/*` branches and will run `npm pack` and archive the output.
3. A "Publish Release" workflow that needs to be manually invoked. It will run `npm publish`, merge the release PR, then create a github release with an autogenerated changelog. This workflow needs to access the npm token as an environment secret and as such needs an approval from a member of the devtools team to run (who is not the person who ran the workflow).
I'm working with IT on getting the actual token, so this wouldn't work until we get it.

chore: create a release workflow

---

.github/release.yml
.github/workflows/assign-labels.yml
.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml

After the first release, this is a follow-up PR that smooths some of the rough edges:
1. Update the `publish-release` workflow to include the url of the package we've uploaded.
2. Update the `prepare-release` to create a PR with a title that conforms to the conventional commit conventions as well as add a label to ignore the PR from the changelog.
3. Add a `release.yml` config to categorize the changelog based on labels.
4. Add a `assign-labels` workflow to assign labels based on PR title. Those labels are later used by the changelog generator.

chore(ci): tweak release workflow

---

.github/workflows/prepare-release.yml
.github/workflows/publish-release.yml
CONTRIBUTING.md

This PR adds a `Contributing.md` that has a releasing section and updates the PR description of the prepare-release workflow with instructions for how to finish the release.
Additionally, it replaces the token used to creating and merging the release PR with the token we have for devtoolsbot. This should result in normal workflows getting run both on the release PR and the main branch after merging.

chore: add better releasing docs

---

src/rfc-8252-http-server.spec.ts
src/rfc-8252-http-server.ts

This appears to be the cause of the failures we're seeing in mongosh. The logs indicate that we're getting duplicate dns addresses, which causes us to fire up two servers, one of which will inevitably fail due to address being in use. Here's the corresponding log message:
```
2025-02-26T17:22:33.225Z connection controller INFO  OIDC-PLUGIN [
{ __value: 1002000028 },
'compass-oidc',
'Resolved hostnames for local server',
{
url: 'http://localhost:37197/redirect',
urlPort: 37197,
hostname: 'localhost',
interfaces: [
{ address: '127.0.0.1', family: 4 },
{ address: '127.0.0.1', family: 4 }
]
}
]
```

fix: filter out duplicate dns results MONGOSH-2027

---

src/integration.spec.ts
src/log-hook.ts
src/plugin.spec.ts
src/plugin.ts
src/types.ts
src/util.ts
test/oidc-test-provider.ts

Ensure that we do not return tokens from a token set that the driver
is currently rejecting (in the sense of calling the OIDC callback
again and referring to it via the driver `refreshToken` property).

fix: handle ID token expiry time and premature expiration MONGOSH-2145 MONGOSH-2147

---

src/plugin.ts
src/rfc-8252-http-server.ts
src/types.ts
tsconfig.json

It came up in conversations that OIDC connections in Compass fail frequently, but we do not have real insight into why that is and what the most common errors are overall.

feat: add `codeName` to all OIDC errors coming from the plugin

---

src/plugin.spec.ts

These seem to have started to fail recently too, without changes to the code itself (i.e. possibly only because of infrastructure or external dependency changes such as Chrome updates).
This is still covered in Github Actions.

chore: skip integration tests for Windows too in Evergreen

---

src/plugin.spec.ts
src/plugin.ts
src/util.ts

`node-fetch` currently does not return a body that is a web/standard `ReadableStream`, which is what openid-client expects. Since it only makes use of this in error cases, no additional cases are broken, but the error message is highly unhelpful in these cases.
Unfortunately, it is not trivial to resolve this without fully wrapping the `node-fetch`, so this provides a limited compatibility layer rather than a full-featured one. (Note – I'm opening the PR with this approach but I'd be up for changing this if somebody feels strongly that we should put in the effort to provide a full layer around `Response`. We can't "just" replace `.body` only because node-fetch's `.text()` and `.json()` methods expect it to be a Node.js stream.)

fix: improve node-fetch compatibility in error cases MONGOSH-2443
